create_clock -period 4.00 -name clk [get_ports clk]
set_property -dict {IOSTANDARD LVCMOS33} [get_ports {clk}]
### PMODS (22 pins)
#set_property -dict {PACKAGE_PIN J12 IOSTANDARD LVCMOS33} [get_ports {result[0]}]
#set_property -dict {PACKAGE_PIN H12 IOSTANDARD LVCMOS33} [get_ports {result[1]}]
#set_property -dict {PACKAGE_PIN J12 IOSTANDARD LVCMOS33} [get_ports {result.sign}]
#set_property -dict {PACKAGE_PIN H12 IOSTANDARD LVCMOS33} [get_ports {result.znan}]
#set_property -dict {PACKAGE_PIN H11 IOSTANDARD LVCMOS33} [get_ports {result.expon[0]}]
#set_property -dict {PACKAGE_PIN G10 IOSTANDARD LVCMOS33} [get_ports {result.expon[1]}]
#set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports {result.expon[2]}]
#set_property -dict {PACKAGE_PIN K12 IOSTANDARD LVCMOS33} [get_ports {result.expon[3]}]
#set_property -dict {PACKAGE_PIN J11 IOSTANDARD LVCMOS33} [get_ports {result.expon[4]}]
#set_property -dict {PACKAGE_PIN J10 IOSTANDARD LVCMOS33} [get_ports {result.expon[5]}]

#set_property PACKAGE_PIN E12 [get_ports {result.expon[6]}]
#set_property PACKAGE_PIN D11 [get_ports {result.expon[7]}]
#set_property PACKAGE_PIN B11 [get_ports {result.mant[0]}]
#set_property PACKAGE_PIN A10 [get_ports {result.mant[1]}]
#set_property PACKAGE_PIN C11 [get_ports {result.mant[2]}]
#set_property PACKAGE_PIN B10 [get_ports {result.mant[3]}]
#set_property PACKAGE_PIN A12 [get_ports {result.mant[4]}]
#set_property PACKAGE_PIN A11 [get_ports {result.mant[5]}]

#set_property PACKAGE_PIN F12 [get_ports {result.mant[6]}]
#set_property PACKAGE_PIN G11 [get_ports {result.mant[7]}]
#set_property PACKAGE_PIN E10 [get_ports {result.mant[8]}]
#set_property PACKAGE_PIN D10 [get_ports {result.mant[9]}]
#set_property PACKAGE_PIN F10 [get_ports {result.mant[10]}]
#set_property PACKAGE_PIN F11 [get_ports {result.mant[11]}]
### Rasbery PI Headers
#set_property PACKAGE_PIN AF10 [get_ports {result.mant[12]}]
#set_property PACKAGE_PIN AG10 [get_ports {result.expon[8]}]
#set_property PACKAGE_PIN AC12 [get_ports {result.expon[9]}]
#set_property  -dict {PACKAGE_PIN AD12 IOSTANDARD LVCMOS33} [get_ports {operanda.sign}]
#set_property  -dict {PACKAGE_PIN AE12 IOSTANDARD LVCMOS33} [get_ports {operanda.znan}]
#set_property  -dict {PACKAGE_PIN AE10 IOSTANDARD LVCMOS33} [get_ports {operandb.sign}]
#set_property  -dict {PACKAGE_PIN AB11 IOSTANDARD LVCMOS33} [get_ports {operandb.znan}]
#set_property  -dict {PACKAGE_PIN AD11 IOSTANDARD LVCMOS33} [get_ports {operanda.expon[0]}]
#set_property  -dict {PACKAGE_PIN AG11 IOSTANDARD LVCMOS33} [get_ports {operandb.expon[0]}]

#set_property -dict {IOSTANDARD LVCMOS33} [get_ports result*]
